import { compute, Line } from "./computation.ts";

const test_input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

const real_input = await Deno.readTextFile("./day-07/input.txt")

if (import.meta.main) {
    console.log("Day 07");
    
    const input = test_input.split("\n");
    const first = new Line(Array(input[0].length).fill(".").join(""));

    const last = input.reduce((p, v) => {
        return compute(p, v);
    }, first);

    console.debug(last);
}